### ISSUE TITLE
Whether to match TorchANI?

### ISSUE THREAD

**Issue by peastman** [peastman/NNPOps#1]
The calculations implemented in TorchANI are different in a couple of ways from what's described in [the paper](https://pubs.rsc.org/en/Content/ArticleLanding/2017/SC/C6SC05720A).  Which one should this code match?

The first difference is that it divides all the radial symmetry functions by 4.  A comment in the code notes this is different from the paper, and says they're doing it to be consistent with NeuroChem.  I have no idea why NeuroChem does it.

This one isn't that big a deal, since the user can easily multiply or divide the functions by 4 if they need to.  The other one is a bigger problem.  When computing the angular symmetry functions, it calculates the angle by taking the dot product of two vectors and using acos().  There are two problems you have to be careful of when doing this.  Because acos() is singular at 1 and -1, the result becomes inaccurate when it gets too close to those extremes.  And if roundoff error should ever cause it to go outside that range, the result is NaN.

This problem is easy to deal with.  You detect when the dot product is too close to 1 or -1, and switch over to using asin() to calculate the angle from the cross product.  This produces accurate results over the entire range.  Unfortunately, that isn't what TorchANI does.

Instead, it uses the hack of just multiplying all dot products by 0.95.  This produces *very* inaccurate results near the extremes.  For example, if the true angle is exactly 0, this will instead produce an angle of about 18 degrees.  It also distorts the results by a smaller amount even for angles that are far from the extremes.

What behavior should we implement here?  Should we match what's in the paper or what's implemented in TorchANI?

**Comment by proteneer** [comment]
If you're using parameters trained via TorchANI we will have to match the "incorrect" way of computing the angles, otherwise there's no guarantee that the features are usable with an existing set of parameters.

**Comment by peastman** [comment]
And if they're trained with some other code, we need to match that one.  I'm going to make this an option so you can get either behavior.

**Comment by raimis** [comment]
We should implement both:
- In short term, we have to be compatible with TorchANI to be able to use ANI-2x and other already trained networks.
- In long term, we should encourage the NNP community to use geometrically correct and numerically stable implementation.

**Comment by peastman** [comment]
I added the option for this.
